# Generated by Django 4.2.6 on 2026-09-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('pay_scale', models.CharField(max_length=20)),
                ('date_of_joining', models.DateField()),
                ('basic_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('posting_place', models.CharField(max_length=100)),
                ('gross_pay', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['serial_number'],
            },
        ),
    ]
