# Generated by Django 4.2.6 on 2026-09-17 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_servicehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='contract_type',
            field=models.CharField(choices=[('short_contract', 'Short Contract'), ('pay_scale', 'Pay Scale'), ('railway_employee', 'Railway Employee'), ('other', 'Other')], default='other', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffmember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='staff_photos/'),
        ),
    ]
