# Generated by Django 4.2.6 on 2026-09-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_staffmember_contract_type_staffmember_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10),
        ),
    ]
