# Generated by Django 4.2.6 on 2026-09-18 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_staffmember_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='separation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('resigned', 'Resigned'), ('terminated', 'Terminated')], default='active', max_length=20),
        ),
    ]
