# Generated by Django 4.2.6 on 2026-09-21 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_staffmember_separation_date_staffmember_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplinaryAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('action_type', models.CharField(choices=[('warning', 'Warning'), ('show_cause', 'Show Cause Notice'), ('penalty', 'Penalty'), ('suspension', 'Suspension'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinary_actions', to='accounts.staffmember')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
