# Generated by Django 4.2.6 on 2026-09-24 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('resigned', 'Resigned'), ('terminated', 'Terminated'), ('repatriated', 'Repatriated')], default='active', max_length=20),
        ),
    ]
